(()=>{
  'use strict';
  const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const date=value=>value?new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'–';
  const localDate=value=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const state={data:null,isAdmin:false};
  const ui={};

  async function api(url,options={}){
    const headers=await window.SiteBriefCloud?.authHeaders?.()||{};const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...headers,...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Anfrage fehlgeschlagen.');return data;
  }
  function message(text='',kind=''){ui.message.textContent=text;ui.message.className=`auth-message ${kind}`.trim()}
  function stats(){const s=state.data?.stats||{};ui.stats.innerHTML=[['Benutzer',s.users||0],['Aktive Abos',s.activeSubscriptions||0],['Projekte',s.projects||0],['KI-Aufrufe',s.generations||0]].map(([label,value])=>`<article><span>${esc(label)}</span><strong>${Number(value).toLocaleString('de-DE')}</strong></article>`).join('')}
  function usage(){const events=state.data?.usage||[],map=new Map();events.forEach(item=>{const key=`${item.provider||'unbekannt'} · ${item.model||'Standardmodell'}`,current=map.get(key)||{count:0,errors:0,duration:0};current.count++;if(!item.success)current.errors++;current.duration+=Number(item.duration_ms)||0;map.set(key,current)});ui.usage.innerHTML=map.size?[...map.entries()].sort((a,b)=>b[1].count-a[1].count).slice(0,12).map(([name,data])=>`<div><span>${esc(name)}<small>${data.errors?` · ${data.errors} Fehler`:''}${data.duration?` · Ø ${Math.round(data.duration/data.count/100)/10} s`:''}</small></span><b>${data.count}</b></div>`).join(''):'<p class="empty-state">Noch keine KI-Nutzung erfasst.</p>'}
  function runs(){const events=(state.data?.usage||[]).slice(0,25);ui.runs.innerHTML=events.map(item=>`<article><div><span>${esc(item.action||'Verarbeitung')} · ${esc(item.provider||'unbekannt')}</span><strong>${esc(item.project_name||item.project_type||'Projekt ohne Namen')}</strong><small>${esc([item.project_type,item.project_goal].filter(Boolean).join(' · ')||item.model||'Keine Projektdetails')} · ${date(item.created_at)}</small>${item.error_message?`<p>${esc(item.error_message)}</p>`:''}</div><i class="${item.success?'active':'blocked'}">${item.success?'Erfolgreich':'Fehler'}</i></article>`).join('')||'<p class="empty-state">Noch keine Verarbeitungen erfasst.</p>'}
  function userRows(){const term=ui.search.value.trim().toLowerCase(),users=(state.data?.users||[]).filter(user=>!term||`${user.email} ${user.profile?.display_name||''} ${user.profile?.company_name||''}`.toLowerCase().includes(term));ui.users.innerHTML=users.map(user=>{const sub=user.subscription||{},blocked=Boolean(user.bannedUntil&&new Date(user.bannedUntil)>new Date()),stripe=Boolean(sub.provider_subscription_id);return `<article class="admin-user" data-user-id="${esc(user.id)}"><div class="admin-user-main"><span>${esc(user.profile?.company_name||user.profile?.display_name||'Benutzerkonto')}</span><strong>${esc(user.email)}</strong><small>Registriert ${date(user.createdAt)} · ${user.projectCount} Projekte · ${user.usageCount} KI-Aufrufe · Abo ${esc(sub.status||'active')}${sub.current_period_end?` bis ${date(sub.current_period_end)}`:''}</small></div><div class="admin-user-status"><b class="plan-pill">${esc((sub.plan||'free').toUpperCase())}</b><i class="${blocked?'blocked':'active'}">${blocked?'Gesperrt':'Aktiv'}</i></div><div class="admin-user-actions"><select data-user-plan><option value="free" ${sub.plan==='free'?'selected':''}>Free</option><option value="pro" ${sub.plan==='pro'?'selected':''}>Pro</option><option value="ultimate" ${sub.plan==='ultimate'?'selected':''}>Ultimate</option></select><button type="button" class="outline-btn mini" data-admin-action="set-plan">Tarif setzen</button><button type="button" class="outline-btn mini" data-admin-action="password">Reset-Mail</button>${stripe?'<button type="button" class="outline-btn mini" data-admin-action="cancel-subscription">Abo kündigen</button><button type="button" class="text-btn danger" data-admin-action="refund-latest">Letzte Zahlung erstatten</button>':''}<button type="button" class="text-btn danger" data-admin-action="${blocked?'unsuspend':'suspend'}">${blocked?'Entsperren':'Sperren'}</button></div></article>`}).join('')||'<p class="empty-state">Keine passenden Benutzer gefunden.</p>'}
  function announcements(){const items=state.data?.announcements||[];ui.announcements.innerHTML=items.map(item=>`<article><div><span>${esc(item.level.toUpperCase())}${item.active?' · AKTIV':''}</span><strong>${esc(item.title)}</strong><p>${esc(item.body)}</p><small>${item.ends_at?`bis ${date(item.ends_at)}`:'ohne Enddatum'}</small></div><button type="button" class="text-btn danger" data-delete-announcement="${esc(item.id)}">Löschen</button></article>`).join('')||'<p class="empty-state">Noch keine Mitteilungen.</p>'}
  function offer(){const item=state.data?.offer||{};ui.offerEnabled.checked=Boolean(item.enabled);ui.offerEyebrow.value=item.eyebrow||'';ui.offerTitle.value=item.title||'';ui.offerDescription.value=item.description||'';ui.offerCta.value=item.cta_label||'';ui.offerTrial.value=item.trial_days||0;ui.offerDiscount.value=item.discount_percent||0;ui.offerCoupon.value=item.stripe_coupon_id||'';ui.offerEnds.value=localDate(item.ends_at)}
  function render(){stats();usage();runs();userRows();announcements();offer()}
  async function load(){message('Admin-Daten werden geladen…');try{state.data=await api('/api/admin-overview');render();message('Aktueller Stand geladen.','good')}catch(error){message(error.message,'error')}}
  async function action(payload,success){message('Änderung wird gespeichert…');try{await api('/api/admin-action',{method:'POST',body:JSON.stringify(payload)});message(success,'good');await load()}catch(error){message(error.message,'error')}}
  function init(){
    Object.assign(ui,{button:$('#adminBtn'),dialog:$('#adminDialog'),message:$('#adminMessage'),stats:$('#adminStats'),usage:$('#adminUsage'),runs:$('#adminRuns'),users:$('#adminUsers'),search:$('#adminUserSearch'),announcements:$('#adminAnnouncements'),offerEnabled:$('#offerEnabled'),offerEyebrow:$('#adminOfferEyebrow'),offerTitle:$('#adminOfferTitle'),offerDescription:$('#adminOfferDescription'),offerCta:$('#adminOfferCta'),offerTrial:$('#adminOfferTrialDays'),offerDiscount:$('#adminOfferDiscount'),offerCoupon:$('#adminOfferCoupon'),offerEnds:$('#adminOfferEndsAt')});
    ui.button.addEventListener('click',()=>{ui.dialog.showModal();load()});$('#adminReloadBtn').addEventListener('click',load);ui.search.addEventListener('input',userRows);
    $$('.admin-tabs button').forEach(button=>button.addEventListener('click',()=>{$$('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===button));$$('.admin-pane').forEach(pane=>pane.classList.toggle('active',pane.dataset.adminPane===button.dataset.adminTab))}));
    ui.users.addEventListener('click',event=>{const button=event.target.closest('[data-admin-action]');if(!button)return;const row=button.closest('[data-user-id]'),userId=row.dataset.userId,type=button.dataset.adminAction;if(type==='set-plan')return action({action:'set-plan',userId,plan:$('[data-user-plan]',row).value},'Tarif wurde geändert.');if(type==='password'&&confirm('Eine Passwort-Reset-Mail an diesen Benutzer senden?'))return action({action:'send-password-reset',userId},'Reset-Mail wurde versendet.');if(type==='cancel-subscription'&&confirm('Das Stripe-Abo wirklich zum Ende des aktuellen Zeitraums kündigen?'))return action({action:'cancel-subscription',userId},'Abo wird zum Laufzeitende gekündigt.');if(type==='refund-latest'&&confirm('Die letzte bezahlte Stripe-Rechnung vollständig erstatten? Diese Aktion kann nicht rückgängig gemacht werden.'))return action({action:'refund-latest',userId},'Die letzte Zahlung wurde erstattet.');if(type==='unsuspend'&&confirm('Benutzer wieder entsperren?'))return action({action:'unsuspend',userId},'Benutzer wurde entsperrt.');if(type==='suspend'){const days=prompt('Wie viele Tage sperren?','30');if(days===null)return;const reason=prompt('Grund der Sperre:','Verstoß gegen die Nutzungsbedingungen');if(reason===null)return;return action({action:'suspend',userId,days:Number(days),reason},'Benutzer wurde gesperrt.')}});
    $('#saveAnnouncementBtn').addEventListener('click',()=>action({action:'save-announcement',title:$('#announcementTitle').value,body:$('#announcementBody').value,level:$('#announcementLevel').value,active:$('#announcementActive').checked,endsAt:$('#announcementEndsAt').value?new Date($('#announcementEndsAt').value).toISOString():null},'Mitteilung wurde gespeichert.'));
    ui.announcements.addEventListener('click',event=>{const button=event.target.closest('[data-delete-announcement]');if(button&&confirm('Mitteilung wirklich löschen?'))action({action:'delete-announcement',id:button.dataset.deleteAnnouncement},'Mitteilung wurde gelöscht.')});
    $('#saveOfferBtn').addEventListener('click',()=>action({action:'save-offer',enabled:ui.offerEnabled.checked,eyebrow:ui.offerEyebrow.value,title:ui.offerTitle.value,description:ui.offerDescription.value,ctaLabel:ui.offerCta.value,trialDays:Number(ui.offerTrial.value),discountPercent:Number(ui.offerDiscount.value),stripeCouponId:ui.offerCoupon.value,endsAt:ui.offerEnds.value?new Date(ui.offerEnds.value).toISOString():null},'Aktion wurde gespeichert.'));
    window.addEventListener('sitebrief:admin',event=>{state.isAdmin=Boolean(event.detail?.isAdmin);ui.button.hidden=!state.isAdmin});
  }

  async function publicContent(){
    try{const [{offer},{announcements}]=await Promise.all([fetch('/api/offer').then(r=>r.json()),fetch('/api/announcements').then(r=>r.json())]);const banner=$('#offerBanner');if(offer){if(!sessionStorage.getItem('sitebrief-offer-hidden')){$('#offerEyebrow').textContent=offer.eyebrow||'AKTION';$('#offerTitle').textContent=offer.title||'';$('#offerDescription').textContent=offer.description||'';$('#offerCta').textContent=offer.cta_label||'Tarife ansehen';banner.hidden=false}const label=offer.cta_label||(offer.trial_days?`${offer.trial_days} Tage kostenlos testen`:'Tarif wählen');if($('#startProCheckoutBtn'))$('#startProCheckoutBtn').textContent=label;if($('#startUltimateCheckoutBtn'))$('#startUltimateCheckoutBtn').textContent=label}const notices=$('#publicNotices');notices.innerHTML=(announcements||[]).map(item=>`<div class="public-notice ${esc(item.level)}"><strong>${esc(item.title)}</strong><span>${esc(item.body)}</span><button type="button" aria-label="Mitteilung schließen">×</button></div>`).join('');notices.addEventListener('click',event=>event.target.closest('button')?.parentElement.remove())}catch{}
  }
  document.addEventListener('DOMContentLoaded',()=>{init();publicContent();$('#offerCta').addEventListener('click',()=>$('#plansDialog')?.showModal());$('#offerClose').addEventListener('click',()=>{$('#offerBanner').hidden=true;sessionStorage.setItem('sitebrief-offer-hidden','1')})});
})();
