(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s);
  let installed=false,busy=false,reposLoaded=false;
  function access(){return window.PromptAiAccess||{plan:'free',isAdmin:false}}
  function canBuild(){const a=access();return a.isAdmin||a.plan==='ultimate'}
  async function headers(){try{return await window.SiteBriefCloud?.authHeaders?.()||{}}catch{return {}}}
  function styles(){if($('#githubSandboxStyles'))return;const s=document.createElement('style');s.id='githubSandboxStyles';s.textContent=`.github-sandbox{margin:14px 0 18px;padding:16px;border:1px solid var(--line);border-radius:14px;background:color-mix(in srgb,var(--surface) 90%,var(--accent) 3%)}.github-sandbox-head span{display:block;color:var(--accent);font-size:9px;font-weight:850;letter-spacing:.12em}.github-sandbox-head strong{display:block;margin-top:4px;font-size:14px}.github-sandbox-head small{display:block;margin-top:4px;color:var(--muted);font-size:9px;line-height:1.5}.github-sandbox-picker{margin-top:13px}.github-sandbox-picker[hidden]{display:none}.github-sandbox-picker select{width:100%;height:42px;border:1px solid var(--line);border-radius:9px;background:var(--input);color:var(--ink);padding:0 10px;font-size:9px}.github-sandbox-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,.45fr) auto;gap:9px;align-items:end;margin-top:13px}.github-sandbox-grid .field{margin:0}.github-sandbox-status{margin:10px 0 0;color:var(--muted);font-size:9px;line-height:1.5}.github-sandbox-status.good{color:var(--good)}.github-sandbox-status.error{color:var(--danger)}@media(max-width:720px){.github-sandbox-grid{grid-template-columns:1fr}.github-sandbox-grid button{width:100%}}
  `;document.head.appendChild(s)}
  function status(text,kind=''){const e=$('#githubSandboxStatus');if(e){e.textContent=text;e.className=`github-sandbox-status ${kind}`.trim()}}
  function show(data){const frame=$('#outcomePreviewFrame'),wrap=$('#outcomeFrameWrap'),learning=$('#outcomeLearning');if(frame){frame.removeAttribute('srcdoc');frame.setAttribute('sandbox','allow-scripts allow-forms allow-modals allow-popups allow-downloads allow-same-origin');frame.src=data.previewUrl}wrap?.classList.add('ready');learning?.classList.add('ready');const open=$('#sandboxOpenBtn');if(open){open.hidden=false;open.onclick=()=>window.open(data.previewUrl,'_blank','noopener,noreferrer')}const details=$('#sandboxBuildDetails');if(details){details.hidden=false;details.innerHTML=`<span>${String(data.framework||'Projekt').toUpperCase()}</span><strong>${data.projectName||data.source||'GitHub-Projekt'}</strong><small>${data.source||'GitHub'} · HTTP ${Number(data.httpStatus)||200}</small>`}}
  async function loadRepoPicker(){
    if(reposLoaded||!canBuild()||!window.SiteBriefCloud?.user)return;
    reposLoaded=true;
    try{
      const h=await headers(),r=await fetch('/api/github-publish',{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify({action:'list-repos'})}),data=await r.json().catch(()=>({}));
      if(!r.ok||!Array.isArray(data.repos)||!data.repos.length)return;
      const picker=$('#githubSandboxPicker'),select=$('#githubSandboxRepoSelect');if(!picker||!select)return;
      select.innerHTML='<option value="">— eigenes Repository wählen —</option>'+data.repos.map(repo=>`<option value="${repo.fullName}">${repo.fullName}${repo.private?' (privat)':''}</option>`).join('');
      picker.hidden=false;
      select.addEventListener('change',()=>{if(select.value){const input=$('#githubSandboxRepo');if(input)input.value=select.value;const ref=$('#githubSandboxRef');if(ref)ref.value=''}});
    }catch{}
  }
  async function build(){if(busy)return;if(!canBuild()){$('#plansDialog')?.showModal();status('GitHub-Sandbox ist in Ultimate verfügbar.','error');return}if(!window.SiteBriefCloud?.user){$('#accountBtn')?.click();status('Bitte zuerst anmelden.','error');return}const repo=$('#githubSandboxRepo')?.value.trim(),ref=$('#githubSandboxRef')?.value.trim();if(!repo){status('Bitte Repository als owner/repo oder GitHub-URL angeben.','error');return}busy=true;$('#githubSandboxBuild').disabled=true;window.PromptAiLoading?.beginTask?.('github-sandbox-build',{title:'Repository wird geprüft und gebaut',kind:'build'});status('Repository wird geladen, geprüft und in der Vercel Sandbox gebaut…');try{const h=await headers(),r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify({action:'sandbox-build',githubRepo:repo,githubRef:ref})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'GitHub-Build fehlgeschlagen.');show(data);status('Build erfolgreich. Die Anwendung läuft jetzt isoliert in der Live-Vorschau.','good')}catch(e){status(e.message||'GitHub-Build fehlgeschlagen.','error')}finally{window.PromptAiLoading?.endTask?.('github-sandbox-build',{title:'Repository-Lauf ist beendet',kind:'build'});busy=false;$('#githubSandboxBuild').disabled=!canBuild()}}
  function enhance(){const card=$('#sandboxPreviewCard');if(!card||$('#githubSandbox'))return false;styles();const section=document.createElement('section');section.id='githubSandbox';section.className='github-sandbox';section.innerHTML='<div class="github-sandbox-head"><span>GITHUB → SANDBOX</span><strong>Repository direkt prüfen</strong><small>Öffentliche Repositories funktionieren ohne Upload. Private Repositories verwenden ausschließlich deine eigene GitHub-Verbindung. Diese Funktion ist in Ultimate enthalten.</small></div><div class="github-sandbox-picker" id="githubSandboxPicker" hidden><label class="field"><span>Eigenes Repository</span><select id="githubSandboxRepoSelect"></select></label></div><div class="github-sandbox-grid"><label class="field"><span>Repository</span><input id="githubSandboxRepo" placeholder="owner/repo oder https://github.com/owner/repo"></label><label class="field"><span>Branch / Tag <em>optional</em></span><input id="githubSandboxRef" placeholder="main"></label><button type="button" class="solid-btn" id="githubSandboxBuild">GitHub-Repo bauen</button></div><p id="githubSandboxStatus" class="github-sandbox-status"></p>';card.insertAdjacentElement('afterend',section);$('#githubSandboxBuild').onclick=build;$('#githubSandboxBuild').disabled=!canBuild();installed=true;loadRepoPicker();return true}
  function init(){if(enhance())return;const o=new MutationObserver(()=>{if(enhance())o.disconnect()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>o.disconnect(),12000);window.addEventListener('promptai:access',()=>{const b=$('#githubSandboxBuild');if(b)b.disabled=!canBuild();loadRepoPicker()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
