(()=>{
  'use strict';
  const STATE_KEY='sitebrief-v6-state',HISTORY_KEY='prompt-ai-project-history-v1',PROMPT_KEY='prompt-ai-prompt-history-v1',CHECKPOINT_KEY='prompt-ai-ui-checkpoint-v2',CONTINUE_KEY='sitebrief-v6-continue-workflow';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  let stateHash='',lastSnapshotAt=0,promptTimer=0,snapshotTimer=0,dialog=null;
  function read(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
  function hash(value){let h=2166136261,s=typeof value==='string'?value:JSON.stringify(value);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
  function stripHeavy(value){
    const clone=JSON.parse(JSON.stringify(value||{}));
    if(Array.isArray(clone.images))clone.images=clone.images.map(x=>({...x,dataUrl:x?.dataUrl?'[stored separately]':x?.dataUrl}));
    if(Array.isArray(clone.documents))clone.documents=clone.documents.map(x=>({...x,text:String(x?.text||'').slice(0,8000),pageImages:[]}));
    if(clone.generatedWebsite?.files)clone.generatedWebsite={...clone.generatedWebsite,files:clone.generatedWebsite.files.map(x=>({path:x.path,content:String(x.content||'').slice(0,4000)})).slice(0,12)};
    return clone;
  }
  function currentState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch{return null}}
  function projectTitle(s){return String(s?.project?.name||s?.projectName||s?.client?.name||s?.project?.description||s?.projectDescription||'Unbenanntes Projekt').trim().slice(0,70)||'Unbenanntes Projekt'}
  function snapshot(force=false){
    const s=currentState();if(!s)return;const clean=stripHeavy(s),sig=hash(clean),now=Date.now();if(!force&&(sig===stateHash||now-lastSnapshotAt<45000))return;stateHash=sig;lastSnapshotAt=now;
    const rows=read(HISTORY_KEY,[]),projectId=String(clean.projectId||clean.currentProjectId||'local');rows.unshift({id:`${now}-${sig}`,projectId,title:projectTitle(clean),step:Number(clean.currentStep)||1,maxStep:Number(clean.maxVisited)||Number(clean.currentStep)||1,mode:clean.mode||'guided',at:now,state:clean});
    const counts=new Map(),kept=[];for(const row of rows){const n=counts.get(row.projectId)||0;if(n>=6)continue;counts.set(row.projectId,n+1);kept.push(row);if(kept.length>=18)break}write(HISTORY_KEY,kept);
  }
  function storePrompt({prompt,title='Master-Prompt',source='master',projectId=''}){
    const value=String(prompt||'').trim();if(value.length<160)return;const sig=hash(value),rows=read(PROMPT_KEY,[]);if(rows.some(x=>x.hash===sig&&Date.now()-x.at<24*60*60*1000))return;const state=currentState()||{};rows.unshift({id:`${Date.now()}-${sig}`,hash:sig,title:String(title||projectTitle(state)).slice(0,100),source,projectId:projectId||String(state.projectId||state.currentProjectId||'local'),at:Date.now(),prompt:value});write(PROMPT_KEY,rows.slice(0,30));saveCloudPrompt(rows[0]);
  }
  async function saveCloudPrompt(row){
    const cloud=window.SiteBriefCloud;if(!cloud?.user||!cloud?.client)return;try{await cloud.client.from('sitebrief_prompt_versions').insert({user_id:cloud.user.id,project_id:row.projectId||'local',project_title:row.title||'',prompt:row.prompt,prompt_hash:row.hash,source:row.source||'master'})}catch{}
  }
  async function cloudPrompts(){const cloud=window.SiteBriefCloud;if(!cloud?.user||!cloud?.client)return[];try{const {data,error}=await cloud.client.from('sitebrief_prompt_versions').select('id,project_id,project_title,prompt,prompt_hash,source,created_at').eq('user_id',cloud.user.id).order('created_at',{ascending:false}).limit(40);if(error)throw error;return (data||[]).map(x=>({id:x.id,projectId:x.project_id,title:x.project_title||'Prompt',prompt:x.prompt,hash:x.prompt_hash,source:x.source,at:new Date(x.created_at).getTime(),cloud:true}))}catch{return[]}}
  function styles(){if($('#projectHistoryStyles'))return;const s=document.createElement('style');s.id='projectHistoryStyles';s.textContent=`.history-state{display:inline-block;margin-left:8px;padding:3px 8px;border-radius:99px;font-size:8px;font-weight:900;letter-spacing:.1em;vertical-align:middle}.history-state.is-done{background:color-mix(in srgb,#2f8f57 16%,transparent);color:#2f8f57}.history-state.is-open{background:color-mix(in srgb,var(--muted) 16%,transparent);color:var(--muted)}.history-dialog{width:min(900px,calc(100vw - 20px));max-height:calc(100dvh - 20px);border:0;padding:0;background:transparent;color:var(--ink)}.history-frame{display:grid;grid-template-rows:auto auto minmax(0,1fr);max-height:calc(100dvh - 20px);border:1px solid var(--line);border-radius:20px;background:var(--paper);overflow:hidden}.history-head{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid var(--line)}.history-head span{font-size:8px;font-weight:850;letter-spacing:.12em;color:var(--accent)}.history-head h2{margin:4px 0 0}.history-close{width:42px;height:42px;border:1px solid var(--line);border-radius:50%;background:var(--surface);color:var(--ink);font-size:22px}.history-tabs{display:flex;gap:4px;padding:10px 16px;border-bottom:1px solid var(--line)}.history-tabs button{border:0;background:transparent;color:var(--muted);padding:9px 11px}.history-tabs button.active{color:var(--ink);border-bottom:2px solid var(--accent)}.history-body{overflow:auto;padding:16px}.history-list{display:grid;gap:9px}.history-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:13px 14px;border:1px solid var(--line);border-radius:13px;background:var(--surface)}.history-row strong,.history-row small{display:block}.history-row small{margin-top:4px;color:var(--muted);font-size:9px}.history-actions{display:flex;gap:7px;flex-wrap:wrap}.history-empty{padding:28px;color:var(--muted);text-align:center}.history-prompt-preview{white-space:pre-wrap;max-height:74px;overflow:hidden;font-size:9px;color:var(--muted);margin-top:6px}.history-restore-shield{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:var(--paper);color:var(--ink)}.history-restore-shield strong{font-size:20px}@media(max-width:700px){.history-dialog{width:100vw;height:100dvh;max-height:none;margin:0}.history-frame{height:100dvh;max-height:none;border:0;border-radius:0}.history-row{grid-template-columns:1fr}.history-actions>*{flex:1}}
  `;document.head.appendChild(s)}
  function ensure(){if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='projectHistoryDialog';dialog.className='history-dialog';dialog.innerHTML='<div class="history-frame"><header class="history-head"><div><span>VERLAUF</span><h2>Projektstände & Prompt-Versionen</h2></div><button type="button" class="history-close" aria-label="Schließen">×</button></header><nav class="history-tabs"><button type="button" class="active" data-history-tab="projects">Projektstände</button><button type="button" data-history-tab="prompts">Prompt-Versionen</button></nav><div class="history-body"><div id="projectHistoryList" class="history-list"></div><div id="promptHistoryList" class="history-list" hidden></div></div></div>';document.body.appendChild(dialog);dialog.querySelector('.history-close').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{e.preventDefault();dialog.close()});$$('[data-history-tab]',dialog).forEach(b=>b.onclick=()=>{$$('[data-history-tab]',dialog).forEach(x=>x.classList.toggle('active',x===b));$('#projectHistoryList').hidden=b.dataset.historyTab!=='projects';$('#promptHistoryList').hidden=b.dataset.historyTab!=='prompts'});dialog.addEventListener('click',handleAction);return dialog}
  function fmt(at){try{return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(at))}catch{return''}}
  // A project counts as finished once it reached the master-prompt step. Older entries predate
  // the stored maxStep, so the step they were saved on decides for them.
  function isDone(row){return Math.max(Number(row?.maxStep)||0,Number(row?.step)||0,Number(row?.state?.maxVisited)||0)>=8}
  async function render(){const d=ensure(),projects=read(HISTORY_KEY,[]);$('#projectHistoryList').innerHTML=projects.length?projects.map(x=>`<article class="history-row"><div><strong>${escapeHtml(x.title)}</strong> <b class="history-state ${isDone(x)?'is-done':'is-open'}">${isDone(x)?'FERTIG':'NOCH OFFEN'}</b><small>${fmt(x.at)} · ${escapeHtml(x.mode)} · Schritt ${Number(x.step)||1}</small></div><div class="history-actions"><button type="button" class="outline-btn mini" data-history-restore="${escapeHtml(x.id)}">Wiederherstellen</button><button type="button" class="text-btn danger" data-history-delete="${escapeHtml(x.id)}">Löschen</button></div></article>`).join(''):'<div class="history-empty">Noch keine automatischen Projektstände gespeichert.</div>';
    const local=read(PROMPT_KEY,[]),remote=await cloudPrompts(),seen=new Set(),prompts=[];for(const x of [...local,...remote]){const key=x.hash||x.id;if(seen.has(key))continue;seen.add(key);prompts.push(x)}prompts.sort((a,b)=>b.at-a.at);d._prompts=prompts;$('#promptHistoryList').innerHTML=prompts.length?prompts.slice(0,40).map(x=>`<article class="history-row"><div><strong>${escapeHtml(x.title||'Prompt')}</strong><small>${fmt(x.at)} · ${escapeHtml(x.source||'master')}${x.cloud?' · Cloud':''}</small><div class="history-prompt-preview">${escapeHtml(String(x.prompt||'').slice(0,260))}</div></div><div class="history-actions"><button type="button" class="outline-btn mini" data-prompt-copy="${escapeHtml(String(x.id))}">Kopieren</button>${x.cloud?`<button type="button" class="text-btn danger" data-prompt-cloud-delete="${escapeHtml(String(x.id))}">Löschen</button>`:`<button type="button" class="text-btn danger" data-prompt-delete="${escapeHtml(String(x.id))}">Löschen</button>`}</div></article>`).join(''):'<div class="history-empty">Noch keine Prompt-Versionen gespeichert.</div>'}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  async function handleAction(e){const restore=e.target.closest('[data-history-restore]'),del=e.target.closest('[data-history-delete]'),copy=e.target.closest('[data-prompt-copy]'),pdel=e.target.closest('[data-prompt-delete]'),cdel=e.target.closest('[data-prompt-cloud-delete]');if(restore){const row=read(HISTORY_KEY,[]).find(x=>x.id===restore.dataset.historyRestore);if(!row)return;const ok=await window.PromptAiDialog?.confirm?.('Diesen gespeicherten Projektstand wiederherstellen? Der aktuelle lokale Stand wird vorher noch einmal gesichert.',{title:'Projektstand wiederherstellen',confirmLabel:'Wiederherstellen'});if(ok){snapshot(true);write(STATE_KEY,row.state);try{localStorage.setItem(CHECKPOINT_KEY,JSON.stringify({mode:row.mode||'guided',step:row.step||1,surface:'workflow',at:Date.now()}));sessionStorage.setItem(CONTINUE_KEY,'1')}catch{}dialog.close();const shield=document.createElement('div');shield.className='history-restore-shield';shield.innerHTML='<strong>Projektstand wird wiederhergestellt…</strong>';document.body.appendChild(shield);setTimeout(()=>location.reload(),180)}return}if(del){write(HISTORY_KEY,read(HISTORY_KEY,[]).filter(x=>x.id!==del.dataset.historyDelete));return render()}if(copy){const row=dialog._prompts?.find(x=>String(x.id)===copy.dataset.promptCopy);if(row)try{await navigator.clipboard.writeText(row.prompt)}catch{}return}if(pdel){write(PROMPT_KEY,read(PROMPT_KEY,[]).filter(x=>String(x.id)!==pdel.dataset.promptDelete));return render()}if(cdel){const cloud=window.SiteBriefCloud;if(cloud?.client&&cloud?.user)try{await cloud.client.from('sitebrief_prompt_versions').delete().eq('user_id',cloud.user.id).eq('id',cdel.dataset.promptCloudDelete)}catch{}return render()}}
  function entry(){const menu=$('#topbarMenu');if(!menu||$('#projectHistoryBtn'))return;const b=document.createElement('button');b.type='button';b.className='text-btn';b.id='projectHistoryBtn';b.textContent='Projektstände';const reset=$('#resetBtn');menu.insertBefore(b,reset||null);b.onclick=async()=>{await render();try{ensure().showModal()}catch{}}}
  function watch(){document.addEventListener('input',()=>{clearTimeout(snapshotTimer);snapshotTimer=setTimeout(()=>snapshot(false),1200)},true);document.addEventListener('change',()=>{clearTimeout(snapshotTimer);snapshotTimer=setTimeout(()=>snapshot(false),900)},true);document.addEventListener('click',e=>{if(e.target.closest('.next-btn,.back-btn,.step-nav'))setTimeout(()=>snapshot(false),600)},true);window.addEventListener('pagehide',()=>snapshot(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')snapshot(true)});const prompt=$('#masterPrompt');if(prompt)prompt.addEventListener('input',()=>{clearTimeout(promptTimer);promptTimer=setTimeout(()=>storePrompt({prompt:prompt.value,title:projectTitle(currentState()||{}),source:'master'}),1800)});window.addEventListener('promptai:prompt-version',e=>storePrompt(e.detail||{}));setInterval(()=>snapshot(false),60000)}
  function init(){styles();entry();ensure();watch();setTimeout(()=>snapshot(false),4000)}
  styles();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
