(()=>{
  'use strict';
  const ADMIN_EMAIL='service.battermann@gmx.de',STATE_KEY='sitebrief-v6-state',CHECKPOINT_KEY='prompt-ai-ui-checkpoint-v2';
  const $=(s,r=document)=>r.querySelector(s);let restoreDone=false,logoutRequested=false,snapshotTimer=0,accessResolved=false;
  function owner(){return String(window.SiteBriefCloud?.user?.email||'').trim().toLowerCase()===ADMIN_EMAIL}
  function effective(){const a=window.PromptAiAccess||{};return {...a,isAdmin:owner()||Boolean(a.isAdmin),plan:owner()?'ultimate':(a.plan||'free'),ownApiKeys:owner()||Boolean(a.ownApiKeys)}}
  function allowedModes(plan){return plan==='ultimate'?['guided','auto','expert']:plan==='pro'?['guided','auto']:['guided']}
  function readJson(storage,key,fallback=null){try{return JSON.parse(storage.getItem(key)||'null')??fallback}catch{return fallback}}
  function style(){if($('#promptStabilityStyles'))return;const s=document.createElement('style');s.id='promptStabilityStyles';s.textContent=`html.prompt-access-pending #upgradeBtn,html.prompt-access-pending #upgradeMenuBtn,html.prompt-access-pending #workflowApp,html.prompt-access-pending .workflow-upgrade,html.prompt-access-pending .quick-upgrade-note,html.prompt-access-pending .quick-tier-block,html.prompt-access-pending #settingsUpgradeNote,html.prompt-access-pending #apiAddonCard,html.prompt-access-pending #currentPlanBadge,html.prompt-access-pending .plan-current{visibility:hidden!important;opacity:0!important;pointer-events:none!important}#workflowApp{transition:opacity .26s ease}.topbar-menu #signOutBtn{width:100%;justify-content:flex-start;border:0!important;background:transparent!important;box-shadow:none!important;padding:10px 12px!important;color:var(--danger,#b84435)!important}@media(prefers-reduced-motion:no-preference){#welcomePage:not([hidden]),#workflowApp:not([hidden]){animation:promptSurfaceIn .28s cubic-bezier(.22,.75,.25,1) both}dialog[open]:not(#welcomeIntroDialog) .dialog-frame{animation:promptDialogIn .25s cubic-bezier(.22,.75,.25,1) both}@keyframes promptSurfaceIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}@keyframes promptDialogIn{from{opacity:0;transform:translateY(8px) scale(.993)}to{opacity:1;transform:none}}}`;document.head.appendChild(s)}
  function pending(){if(!accessResolved)document.documentElement.classList.add('prompt-access-pending')}
  function ready(){accessResolved=true;document.documentElement.classList.remove('prompt-access-pending');document.documentElement.classList.add('prompt-access-ready')}
  function checkpoint(){const mode=$('.mode-switch button.active')?.dataset.mode||'',step=Number($('.step-panel.active')?.dataset.stepPanel||1),workflow=$('#workflowApp'),surface=workflow&&!workflow.hidden?'workflow':'welcome';try{localStorage.setItem(CHECKPOINT_KEY,JSON.stringify({mode,step,surface,at:Date.now()}))}catch{}}
  function scheduleCheckpoint(){clearTimeout(snapshotTimer);snapshotTimer=setTimeout(checkpoint,120)}
  function forceSave(){const model=$('#generatorModel');if(model)model.dispatchEvent(new Event('input',{bubbles:true}));checkpoint()}
  function normalizeAccess(bundle){if(!bundle||typeof bundle!=='object')return bundle;const sub=bundle.subscription||{},isOwner=owner(),active=['active','trialing'].includes(sub.status),paid=active&&['pro','ultimate'].includes(sub.plan)?sub.plan:'free',plan=isOwner?'ultimate':paid,ownApiKeys=isOwner||plan==='ultimate'||Boolean(sub.ownApiKeys),personal=Array.isArray(bundle.aiConnections)?bundle.aiConnections.filter(x=>!x.system):[],config=window.SiteBriefCloud?.config||{},systemProfiles=Array.isArray(config.systemAiProfiles)?config.systemAiProfiles:[],providers=[...new Set([...(config.previewProviders||[]),...(config.systemAiProviders||[]),...systemProfiles.filter(x=>x.enabled!==false).map(x=>x.provider)])],merged=[...personal];for(const provider of providers)if(provider&&!merged.some(x=>x.provider===provider))merged.push({provider,last4:'zentral',updated_at:null,system:true});bundle.aiConnections=merged;bundle.subscription={...sub,plan,isAdmin:isOwner||Boolean(sub.isAdmin),ownApiKeys};window.PromptAiAccess={...(window.PromptAiAccess||{}),plan,isAdmin:isOwner||Boolean(sub.isAdmin),ownApiKeys,apiKeySlots:Math.max(0,Number(sub.apiKeySlots)||0),hasPersonalAi:personal.length>0};queueMicrotask(()=>{window.dispatchEvent(new CustomEvent('sitebrief:admin',{detail:{isAdmin:window.PromptAiAccess.isAdmin}}));window.dispatchEvent(new CustomEvent('promptai:access',{detail:window.PromptAiAccess}))});return bundle}
  function wrapBundle(){const cloud=window.SiteBriefCloud;if(!cloud?.loadUserBundle||cloud.loadUserBundle.__promptStableAccess)return false;const native=cloud.loadUserBundle.bind(cloud);const wrapped=async(...args)=>normalizeAccess(await native(...args));wrapped.__promptStableAccess=true;cloud.loadUserBundle=wrapped;return true}
  function resolveBoot(){pending();const cloudReady=window.SiteBriefCloudReady;if(cloudReady?.then)cloudReady.then(async result=>{wrapBundle();if(!result?.user){ready();return}try{await window.SiteBriefCloud.loadUserBundle()}catch{}setTimeout(()=>{if(!accessResolved)ready()},8000)}).catch(()=>ready());else setTimeout(()=>{wrapBundle();if(!window.SiteBriefCloud?.user)ready()},1800)}
  function freshStartHandoffPending(){try{return Boolean(sessionStorage.getItem('prompt-ai-new-project-mode-v2')||sessionStorage.getItem('prompt-ai-mode-handoff-v1'))}catch{return false}}
  function restore(){
    if(restoreDone)return;
    if(!freshStartHandoffPending()){
      const access=effective(),saved=readJson(localStorage,STATE_KEY,{})||{},cp=readJson(localStorage,CHECKPOINT_KEY,{})||{},wanted=String(saved.mode||cp.mode||'guided');if(allowedModes(access.plan).includes(wanted)){const b=$(`.mode-switch button[data-mode="${CSS.escape(wanted)}"]`);if(b&&!b.disabled&&!b.classList.contains('locked')&&!b.classList.contains('active'))b.click()}const savedAgent=String(saved.targetAgent||''),agent=savedAgent?$(`#agentSelector [data-agent="${CSS.escape(savedAgent)}"]`):null;if(agent&&!agent.hidden&&!agent.disabled&&!agent.classList.contains('active'))agent.click();const out=String(saved.outputTarget||''),output=out?$(`#outputTargetSelector [data-output="${CSS.escape(out)}"]`):null;if(output&&!output.classList.contains('plan-locked')&&!output.classList.contains('active'))output.click();const step=Number(saved.currentStep||cp.step||0),stepButton=step?$(`.step-nav[data-step="${step}"]`):null;if(stepButton&&!stepButton.hidden&&!stepButton.disabled)stepButton.click();if(cp.surface==='workflow'&&Date.now()-Number(cp.at||0)<12*60*60*1000){const welcome=$('#welcomePage'),workflow=$('#workflowApp');if(workflow?.hidden){if(welcome)welcome.hidden=true;workflow.hidden=false}}
    }
    restoreDone=true;ready();checkpoint()
  }
  function adminChrome(){const b=$('#adminBtn'),d=$('#adminDialog'),isAdmin=effective().isAdmin;if(b)b.hidden=!isAdmin;if(!isAdmin&&d?.open)d.close()}
  function sessionChrome(){adminChrome()}
  function moveSignOut(){const b=$('#signOutBtn'),menu=$('#topbarMenu');if(!b||!menu)return;if(b.parentElement!==menu){menu.appendChild(b);if(b.hidden===false&&!window.SiteBriefCloud?.user)b.hidden=true}b.className='text-btn menu-signout';b.textContent='Abmelden';sessionChrome()}
  function closeMenu(){const m=$('#topbarMenu'),t=$('#topbarMenuToggle');m?.classList.remove('open');t?.setAttribute('aria-expanded','false')}
  function loginAfterLogout(){setTimeout(()=>{document.querySelectorAll('dialog[open]').forEach(d=>{if(d.id!=='accountDialog')try{d.close()}catch{}});const d=$('#accountDialog');if(!d)return;d.classList.remove('guest-gate','auth-transitioning');if($('#accountLoggedOut'))$('#accountLoggedOut').hidden=false;if($('#accountLoggedIn'))$('#accountLoggedIn').hidden=true;if($('#accountDialogKicker'))$('#accountDialogKicker').textContent='KONTO';if($('#accountDialogTitle'))$('#accountDialogTitle').textContent='Anmelden';try{if(!d.open)d.showModal()}catch{}},80)}
  function bindLogout(){const b=$('#signOutBtn');if(b)b.addEventListener('click',()=>{logoutRequested=true;forceSave();closeMenu();setTimeout(()=>{if(logoutRequested&&!window.SiteBriefCloud?.user){logoutRequested=false;loginAfterLogout()}},900)});window.SiteBriefCloud?.subscribe?.((event,payload)=>{if(event!=='auth')return;sessionChrome();if(!payload?.user&&logoutRequested){logoutRequested=false;loginAfterLogout()}})}
  function bindAdmin(){document.addEventListener('click',e=>{const b=e.target.closest?.('#adminBtn');if(!b||!effective().isAdmin)return;setTimeout(()=>{const d=$('#adminDialog');try{if(d&&!d.open)d.showModal()}catch{};setTimeout(()=>$('#adminReloadBtn')?.click(),40)},0)},true)}
  function tracking(){document.addEventListener('click',scheduleCheckpoint,true);document.addEventListener('input',scheduleCheckpoint,true);document.addEventListener('change',scheduleCheckpoint,true);window.addEventListener('pagehide',forceSave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')forceSave()})}
  function events(){window.addEventListener('promptai:access',()=>{accessResolved=true;sessionChrome();setTimeout(restore,40)});window.addEventListener('sitebrief:admin',sessionChrome);window.addEventListener('promptai:system-ai-ready',()=>{restoreDone=false;if(window.SiteBriefCloud?.user)window.SiteBriefCloud.loadUserBundle?.().catch?.(()=>{})})}
  function init(){style();wrapBundle();moveSignOut();bindLogout();bindAdmin();tracking();events();sessionChrome();if(!window.SiteBriefCloud?.user&&window.SiteBriefCloud?.configured)ready()}
  window.PromptAiForceCheckpoint=forceSave;
  pending();style();resolveBoot();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
