import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const text=p=>readFile(path.join(root,p),'utf8');
test('all shipped JavaScript parses',async()=>{const files=[];for(const dir of ['.','api','server'])for(const name of await readdir(path.join(root,dir)))if(name.endsWith('.js'))files.push(path.join(root,dir,name));for(const file of files)execFileSync(process.execPath,['--check',file],{stdio:'pipe'})});
test('Hobby deployment stays within 12 API functions',async()=>{const files=(await readdir(path.join(root,'api'))).filter(x=>x.endsWith('.js'));assert.ok(files.length<=12,`found ${files.length} API functions`)});
test('single generation API routes all heavy features',async()=>{const src=await text('api/generate.js');for(const action of ['preview-image','sandbox-build','free-prompt'])assert.match(src,new RegExp(action));assert.match(src,/freePrompt\(req,res\)/)});
test('system AI supports dedicated free prompt task',async()=>{const src=await text('server/system-ai-profiles.js');assert.match(src,/freeprompt/);assert.match(src,/free-prompt/)});
test('new project mode is selected once and switcher stays hidden',async()=>{const src=await text('project-start-ui.js');assert.match(src,/#modeSwitch\{display:none!important\}/);for(const mode of ['guided','auto','expert'])assert.match(src,new RegExp(`data-project-mode=\\"${mode}\\"`))});
test('workflow separates revision and built project tools',async()=>{const src=await text('workflow-cleanup.js');assert.match(src,/#stepPrompt>#revisionStudio\{display:none!important\}/);assert.match(src,/workspacePreviewBtn/);assert.match(src,/Master-Prompt wird generiert/)});
test('access boot uses fast bundle before stability UI',async()=>{const src=await text('admin-console.js'),fast=src.indexOf('cloud-fast-bundle.js'),stability=src.indexOf('stability-ui.js');assert.ok(fast>=0&&fast<stability);assert.doesNotMatch(src,/owner-access\.js/)});
test('free prompt UI offers broad categories, presets and Pro enrichment',async()=>{const src=await text('free-prompt-ui.js'),presets=await text('free-prompt-presets.js');for(const word of ['Musik / Song','Video / Film','Präsentation / PowerPoint','Code / App','Eigener Typ'])assert.ok(src.includes(word));assert.match(src,/Free bleibt bewusst einfach/);assert.match(presets,/Schnellstart/)});
test('service worker caches feature-freeze shell',async()=>{const src=await text('sw.js');assert.match(src,/prompt-ai-shell-v25/);for(const file of ['free-prompt-ui.js','cloud-fast-bundle.js','project-history.js','github-sandbox.js'])assert.ok(src.includes(file))});
test('sandbox supports uploaded ZIP and GitHub repository without another API route',async()=>{const src=await text('server/sandbox-build.js');assert.match(src,/githubRepo/);assert.match(src,/storagePath/);assert.match(src,/parseRepo/)});
test('central image routing supports gateway, OpenAI, Gemini and Cloudflare',async()=>{const src=await text('server/preview-image.js');for(const p of ['gateway','openai','gemini','cloudflare'])assert.ok(src.includes(p));assert.match(src,/images\/generations/)});
test('access gate waits for resolved session instead of flashing Free',async()=>{const src=await text('stability-ui.js');assert.match(src,/prompt-access-pending/);assert.match(src,/8000/);assert.match(src,/isOwner\?'ultimate':paid/)});
test('Stripe checkout returns to the app and keeps add-on gated to Pro',async()=>{const src=await text('api/checkout.js');assert.match(src,/checkout=success/);assert.match(src,/plan!=='pro'/);assert.match(src,/new URL\(normalized\)\.origin/)});
test('prompt history and learning controls remain user-owned',async()=>{const history=await text('project-history.js'),learning=await text('learning-controls.js');assert.match(history,/sitebrief_prompt_versions/);assert.match(history,/user_id/);assert.match(learning,/sitebrief_learning_examples/);assert.match(learning,/\.eq\('user_id',cloud\.user\.id\)/)});
