const {resolveProviderKey}=require('./provider-key');
const {getEntitlements}=require('./entitlements');
const {rateLimit}=require('./rate-limit');
const {logUsage}=require('./usage');
const {serviceFetch}=require('./admin');
const {listProfiles}=require('./system-ai-profiles');

function domainHint(project={}){const text=`${project.description||''} ${project.type||''} ${project.goal||''}`.toLowerCase();if(/handwerk|elektr|hausmeister|garten|reparatur|maler|sanitär|tischler|bau\b|montage/.test(text))return 'real hands-on trade or service work, tools, materials, outdoor work or work in progress';if(/restaurant|café|cafe|döner|doener|pizza|bistro|küche|food|imbiss|bar\b|bäck/.test(text))return 'real food, ingredients, kitchen or dining atmosphere';if(/friseur|beauty|kosmetik|nagel|nail|barber|salon|spa\b/.test(text))return 'a credible beauty, salon or treatment environment';if(/fitness|gym|training|sport|crossfit/.test(text))return 'training, gym space or athletic energy';if(/web-?app|software|saas|dashboard|tool\b|plattform|portal/.test(text))return 'the digital product interface and its real workflow';return 'the exact real subject matter described by the project brief'}
function promptFor(project={},concept={}){const brand=String(project.name||project.type||'Website').slice(0,42),headline=String(concept.headline||project.goal||'').slice(0,70);return `Create a flat 2D screenshot of a finished website homepage at 16:9. It must be a straight-on digital website design, never a photograph of a monitor, laptop, phone, tablet, desk, room or device mockup. No browser chrome, perspective, floating screen, moodboard or collage.\n\nPROJECT SUBJECT: ${domainHint(project)}.\nProject name: ${brand}\nProject type: ${project.type||'Website'}\nGoal: ${project.goal||''}\nAudience: ${project.audience||''}\nBrief: ${project.description||''}\nSpecial wish: ${project.special||''}\n\nCHOSEN DIRECTION\nName: ${concept.name||''}\nMood: ${concept.mood||''}\nLayout: ${concept.layout||''}\nLayout variant: ${concept.layoutVariant||''}\nHero: ${concept.hero||''}\nTypography: ${concept.type||''}\nPalette: ${(concept.palette||[]).join(', ')}\nHeadline: ${headline}\n\nMake the composition bespoke to this exact project. Avoid generic SaaS layouts, centered badge-headline-two-button heroes, card grids, glassmorphism, gradient blobs, neon glow and excessive rounded rectangles. Use one dominant project-relevant visual idea and strong hierarchy. If text cannot be rendered perfectly, render no text instead of fake or garbled letters. If text is shown, use only the exact brand name "${brand}" and exact headline "${headline}". Never invent reviews, statistics, awards, company facts or legal claims.`}
function safeModel(value,fallback){const model=String(value||fallback||'').trim();return model&&model.length<190&&/^[a-zA-Z0-9@._:/-]+$/.test(model)?model:fallback}
async function legacyRoutes(){try{return (await serviceFetch('/rest/v1/sitebrief_preview_ai_routes?select=id,label,provider,model,priority,enabled&enabled=eq.true&order=priority.asc')).data||[]}catch{return []}}
async function routes(){const profiles=await listProfiles('image');if(profiles.length)return profiles;return legacyRoutes()}
async function gemini(key,model,prompt){const selected=safeModel(model,'gemini-3.1-flash-image').replace(/^models\//,'');const response=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({model:selected,input:prompt,response_format:{type:'image',mime_type:'image/jpeg',aspect_ratio:'16:9',image_size:'1K'}})}),data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error?.message||'Gemini image request failed'),{status:response.status});let image=data.output_image?.data?data.output_image:null;if(!image)for(const step of data.steps||[])for(const block of step.content||[])if(block.type==='image'&&block.data){image=block;break}if(!image)throw new Error('Gemini hat kein Bild zurückgegeben');return `data:${image.mime_type||image.mimeType||'image/jpeg'};base64,${image.data}`}
async function cloudflare(key,model,prompt){const split=key.indexOf(':');if(split<1)throw new Error('Cloudflare-Verbindung ist unvollständig.');const accountId=key.slice(0,split),token=key.slice(split+1),selected=safeModel(model,'@cf/black-forest-labs/flux-1-schnell');if(!selected.startsWith('@cf/'))throw new Error('Ungültiges Cloudflare Workers AI Bildmodell.');const seed=Math.floor(Math.random()*2147483647),response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(accountId)}/ai/run/${selected}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt.slice(0,2048),steps:8,width:1280,height:720,seed})}),data=await response.json().catch(()=>({}));if(!response.ok||data?.success===false)throw Object.assign(new Error(data?.errors?.[0]?.message||'Cloudflare image request failed'),{status:response.status||500});if(!data?.result?.image)throw new Error('Cloudflare hat kein Bild zurückgegeben');return `data:image/jpeg;base64,${data.result.image}`}
async function openAiCompatibleImage(key,model,prompt,baseUrl){const selected=safeModel(model,baseUrl.includes('ai-gateway')?'openai/gpt-image-2':'gpt-image-1'),response=await fetch(`${baseUrl}/images/generations`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:selected,prompt,n:1,size:'1536x1024',response_format:'b64_json'})}),data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data?.error?.message||data?.message||'Bildmodell konnte kein Bild erzeugen.'),{status:response.status});const item=data?.data?.[0];if(item?.b64_json)return `data:image/png;base64,${item.b64_json}`;if(item?.url){const image=await fetch(item.url);if(!image.ok)throw new Error('Bild wurde erzeugt, konnte aber nicht geladen werden.');const buffer=Buffer.from(await image.arrayBuffer()),type=image.headers.get('content-type')||'image/png';return `data:${type};base64,${buffer.toString('base64')}`}throw new Error('Das Bildmodell hat kein Bild zurückgegeben.')}
async function renderImage(provider,key,model,prompt){if(provider==='gemini')return gemini(key,model,prompt);if(provider==='cloudflare')return cloudflare(key,model,prompt);if(provider==='openai')return openAiCompatibleImage(key,model,prompt,'https://api.openai.com/v1');if(provider==='gateway')return openAiCompatibleImage(key,model,prompt,'https://ai-gateway.vercel.sh/v1');throw new Error('Nicht unterstützte Bild-KI.')}

module.exports=async function previewImage(req,res){
  res.setHeader('Cache-Control','no-store, private');if(!rateLimit(req,res,{key:'preview-image',limit:12,windowMs:60000}))return;
  const started=Date.now(),body=req.body||{},project=body.project||{},requested=String(body.imageProvider||'auto').toLowerCase();let usage={action:'preview-image',provider:requested,model:'',project};
  try{
    const entitlement=await getEntitlements(req);if(entitlement.plan==='free'&&!entitlement.ownApiKeys)return res.status(403).json({error:'KI-Bildvorschauen sind ab Pro verfügbar.'});
    let candidates=await routes();if(['gateway','openai','gemini','cloudflare'].includes(requested))candidates=candidates.filter(x=>x.provider===requested);
    if(!candidates.length){candidates=[{provider:'gemini',model:'gemini-3.1-flash-image',label:'Gemini Standard',priority:998},{provider:'cloudflare',model:'@cf/black-forest-labs/flux-1-schnell',label:'Cloudflare Fallback',priority:999}]}
    const errors=[];for(const route of candidates){try{const useOwn=body.useOwnApi===true&&entitlement.ownApiKeys,resolved=await resolveProviderKey(req,route.provider,{systemOnly:!useOwn});if(!resolved.key)throw new Error(`Für ${route.label||route.provider} ist kein aktiver Zugang vorhanden.`);usage={action:'preview-image',provider:route.provider,model:route.model,project};const prompt=promptFor(project,body.concept||{}),imageDataUrl=await renderImage(route.provider,resolved.key,route.model,prompt);res.setHeader('X-SiteBrief-AI-Key-Source',resolved.source);await logUsage(req,{...usage,durationMs:Date.now()-started});return res.status(200).json({imageDataUrl,provider:route.provider,model:route.model,route:route.label||''})}catch(error){errors.push(`${route.label||route.model}: ${error.message}`)}}
    throw Object.assign(new Error(`Keine Vorschau-KI konnte ein Bild erzeugen. ${errors.join(' | ')}`),{status:503});
  }catch(error){await logUsage(req,{...usage,success:false,durationMs:Date.now()-started,error:error.message||'Preview generation failed'});return res.status(error.status||500).json({error:error.message||'Preview generation failed'})}
};
