const crypto=require('crypto');const {SUPABASE_URL}=require('../server/supabase-user');const {stripeGet}=require('../server/stripe-rest');
function rawBody(req){return new Promise((resolve,reject)=>{const chunks=[];req.on('data',c=>chunks.push(Buffer.from(c)));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
function verify(body,header,secret){const parts=Object.fromEntries(String(header||'').split(',').map(x=>x.split('='))),t=parts.t,s=parts.v1;if(!t||!s)return false;const expected=crypto.createHmac('sha256',secret).update(`${t}.${body}`).digest('hex');return expected.length===s.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(s))&&Math.abs(Date.now()/1000-Number(t))<300}
function service(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||'';if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY fehlt');return {key,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'}}}
async function patchSubscription(filter,payload){const {headers}=service(),r=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_subscriptions?${filter}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({...payload,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Abo konnte nicht gespeichert werden')}
async function upsertAddon(userId,payload){const {headers}=service(),r=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_addons?on_conflict=user_id,addon`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,addon:'own_api_keys',...payload,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Add-on konnte nicht gespeichert werden')}
// Der Einzelcheck war ein Fremdkoerper: eine einmalige Pruefung in einem Abo-Produkt - und seit
// Free einen echten KI-Lauf im Monat hat, verkauft er nichts mehr, was es nicht schon gibt. Aus
// demselben Kauf wird jetzt Monatsvorrat: eine Million Einheiten oben drauf. Alte Kaeufe mit dem
// alten Produktnamen landen an derselben Stelle.
// 4,99 EUR fuer eine Million haette Ultimate untergraben: Pro plus vier Aufladungen waere bei
// gleichem Volumen ~41 EUR statt 55 EUR gewesen. Ultimate kostet 34 EUR mehr als Pro fuer 3,5
// Mio zusaetzliche Einheiten, also rund 10 EUR je Million - die Aufladung liegt jetzt auf
// derselben Rate: 750.000 fuer 7,99 EUR (rund 10,65 EUR je Million).
const TOP_UP_UNITS=750000;
async function addBudgetTopUp(userId,purchaseId,product){
  const {headers}=service();
  const read=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_user_admin_state?select=monthly_token_bonus&user_id=eq.${encodeURIComponent(userId)}&limit=1`,{headers});
  const rows=read.ok?await read.json().catch(()=>[]):[];
  const current=Math.max(0,Number(rows?.[0]?.monthly_token_bonus)||0);
  const r=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_user_admin_state?on_conflict=user_id`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,monthly_token_bonus:current+TOP_UP_UNITS,updated_at:new Date().toISOString()})});
  if(!r.ok)throw new Error('Monatsvorrat konnte nicht gutgeschrieben werden');
  return {purchaseId,product,units:TOP_UP_UNITS};
}
function browserHome(req){const host=String(req.headers['x-forwarded-host']||req.headers.host||'www.prompt-ai.app').trim();return `https://${host}/`}
function stripeStatus(o,deleted=false){if(deleted)return'canceled';return ['active','trialing'].includes(o.status)?o.status:o.status==='past_due'?'past_due':'canceled'}
function stripePeriod(o){const seconds=o.status==='trialing'&&o.trial_end?o.trial_end:o.current_period_end;return seconds?new Date(seconds*1000).toISOString():null}
async function subscriptionSnapshot(id){if(!id)return null;try{return await stripeGet(`subscriptions/${encodeURIComponent(id)}`)}catch{return null}}
async function handler(req,res){if(req.method==='GET')return res.redirect(302,browserHome(req));if(req.method!=='POST')return res.status(405).end();try{const raw=await rawBody(req),secret=process.env.STRIPE_WEBHOOK_SECRET||'';if(!secret||!verify(raw,req.headers['stripe-signature'],secret))return res.status(400).json({error:'Invalid signature'});const event=JSON.parse(raw.toString()),o=event.data?.object||{},deleted=event.type==='customer.subscription.deleted',subscriptionCreated=event.type==='customer.subscription.created',subscriptionUpdated=event.type==='customer.subscription.updated';if(event.type==='checkout.session.completed'){const userId=o.client_reference_id||o.metadata?.user_id,paid=['paid','no_payment_required'].includes(o.payment_status),trialDays=Math.max(0,Number(o.metadata?.trial_days)||0),trialing=trialDays>0;if(paid&&o.metadata?.product==='single_review'||product==='top_up')await addBudgetTopUp(userId,o.id,product);else if(paid&&o.metadata?.addon==='own_api_keys')await upsertAddon(userId,{status:'active',quantity:Math.max(1,Math.min(4,Number(o.metadata?.slots)||1)),provider_customer_id:o.customer,provider_subscription_id:o.subscription});else if(paid&&['pro','ultimate'].includes(o.metadata?.plan)){const snapshot=await subscriptionSnapshot(o.subscription),status=snapshot?stripeStatus(snapshot):trialing?'trialing':'active',period=snapshot?stripePeriod(snapshot):(trialing?new Date(Date.now()+trialDays*86400000).toISOString():null);await patchSubscription(`user_id=eq.${encodeURIComponent(userId)}`,{plan:o.metadata.plan,status,provider:'stripe',provider_customer_id:o.customer,provider_subscription_id:o.subscription,current_period_end:period})}}else if(subscriptionCreated||subscriptionUpdated||deleted){const status=stripeStatus(o,deleted),period=stripePeriod(o);if(o.metadata?.addon==='own_api_keys')await upsertAddon(o.metadata?.user_id,{status,quantity:Math.max(1,Math.min(4,Number(o.items?.data?.[0]?.quantity)||Number(o.metadata?.slots)||1)),provider_customer_id:o.customer,provider_subscription_id:o.id,current_period_end:period});else{const payload={status,current_period_end:period,provider_customer_id:o.customer,provider_subscription_id:o.id};if(['pro','ultimate'].includes(o.metadata?.plan))payload.plan=o.metadata.plan;const userId=o.metadata?.user_id,filter=subscriptionCreated&&userId?`user_id=eq.${encodeURIComponent(userId)}`:`provider_subscription_id=eq.${encodeURIComponent(o.id)}`;await patchSubscription(filter,payload)}}return res.status(200).json({received:true})}catch(error){return res.status(500).json({error:error.message||'Webhook failed'})}}
module.exports=handler;module.exports.config={api:{bodyParser:false}};
