const crypto=require('crypto');const {SUPABASE_URL}=require('../server/supabase-user');
function rawBody(req){return new Promise((resolve,reject)=>{const chunks=[];req.on('data',c=>chunks.push(Buffer.from(c)));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
function verify(body,header,secret){const parts=Object.fromEntries(String(header||'').split(',').map(x=>x.split('='))),t=parts.t,s=parts.v1;if(!t||!s)return false;const expected=crypto.createHmac('sha256',secret).update(`${t}.${body}`).digest('hex');return expected.length===s.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(s))&&Math.abs(Date.now()/1000-Number(t))<300}
function service(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||'';if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY fehlt');return {key,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'}}}
async function patchSubscription(filter,payload){const {headers}=service(),r=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_subscriptions?${filter}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({...payload,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Abo konnte nicht gespeichert werden')}
async function upsertAddon(userId,payload){const {headers}=service(),r=await fetch(`${SUPABASE_URL}/rest/v1/sitebrief_addons?on_conflict=user_id,addon`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:userId,addon:'own_api_keys',...payload,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Add-on konnte nicht gespeichert werden')}
async function addReviewCredit(userId,purchaseId){const {headers}=service(),r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/sitebrief_add_review_credit`,{method:'POST',headers,body:JSON.stringify({p_user_id:userId,p_purchase_id:purchaseId,p_amount:1})});if(!r.ok)throw new Error('Einzelprüfung konnte nicht gutgeschrieben werden')}
function browserHome(req){const host=String(req.headers['x-forwarded-host']||req.headers.host||'prompt-prompter.vercel.app').trim();return `https://${host}/`}
async function handler(req,res){if(req.method==='GET')return res.redirect(302,browserHome(req));if(req.method!=='POST')return res.status(405).end();try{const raw=await rawBody(req),secret=process.env.STRIPE_WEBHOOK_SECRET||'';if(!secret||!verify(raw,req.headers['stripe-signature'],secret))return res.status(400).json({error:'Invalid signature'});const event=JSON.parse(raw.toString()),o=event.data?.object||{},deleted=event.type==='customer.subscription.deleted';if(event.type==='checkout.session.completed'){const userId=o.client_reference_id||o.metadata?.user_id,paid=['paid','no_payment_required'].includes(o.payment_status),trialing=Number(o.metadata?.trial_days)>0;if(paid&&o.metadata?.product==='single_review')await addReviewCredit(userId,o.id);else if(paid&&o.metadata?.addon==='own_api_keys')await upsertAddon(userId,{status:'active',provider_customer_id:o.customer,provider_subscription_id:o.subscription});else if(paid&&['pro','ultimate'].includes(o.metadata?.plan))await patchSubscription(`user_id=eq.${encodeURIComponent(userId)}`,{plan:o.metadata.plan,status:trialing?'trialing':'active',provider:'stripe',provider_customer_id:o.customer,provider_subscription_id:o.subscription})}else if(event.type==='customer.subscription.updated'||deleted){const status=deleted?'canceled':(['active','trialing'].includes(o.status)?o.status:o.status==='past_due'?'past_due':'canceled'),period=o.current_period_end?new Date(o.current_period_end*1000).toISOString():null;if(o.metadata?.addon==='own_api_keys')await upsertAddon(o.metadata?.user_id,{status,provider_customer_id:o.customer,provider_subscription_id:o.id,current_period_end:period});else await patchSubscription(`provider_subscription_id=eq.${encodeURIComponent(o.id)}`,{status,current_period_end:period})}return res.status(200).json({received:true})}catch(error){return res.status(500).json({error:error.message||'Webhook failed'})}}
module.exports=handler;module.exports.config={api:{bodyParser:false}};
